disabled_rules: # rule identifiers to exclude from running
    - force_cast
    - force_try
    - trailing_whitespace
    - type_name
    - vertical_whitespace

excluded: # paths to ignore during linting. Takes precedence over `included`.
    - Pods
    - R.generated.swift
